version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11

    working_directory: /go/src/github.com/moul/grpcbin
    steps:
      - checkout
      - run: make install
      - run: go get -v -t .
      - run: make test
      # - run: make integration
      - run: go get -u github.com/alecthomas/gometalinter
      - run: gometalinter --install
      - run: make lint